### ISSUE TITLE
Look at possibility for handling STID 404 when fetching documents

### ISSUE THREAD

**Issue by PtjeEquinor** [equinor/mad-expo-core#112]
If we request a STID document on a plant&tag and there is no document in STID, they return 404 instead of []. 
To avoid handeling the cases in a catch we should consider adding functionality here or maybe contacting STID people to find out why they are returning 404 when no data is found.

workaround code in Workorders 
api.js:27

`export function getEchoAppLink(instCode, tagNo) {
  const path = `/${instCode}/tag?tagNo=${tagNo}`;
  return stidApi
    .get(path)
    .then(handleResponse)
    .catch((e) => (e.toString().includes("404") ? [] : console.log(e)));
}`

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
