### ISSUE TITLE
Look for secrets in commit history

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#122]
In preparation for publishing this project to `npm` we need to look for secrets in our commit history. If there are any, we can use [bfg-repo-cleaner/](https://rtyley.github.io/bfg-repo-cleaner/) to remove them from the commit history.

**Comment by tormodAase** [comment]
I've looked through all commits and could not find any secrets. However, to be extra safe, another person should look as well. @dansvend Do you want to do it?

**Comment by dansvend** [comment]
@tormodAase I've also looked through all commits and could not find any secrets 👌
