### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#127]
Create a system for handling notifications. This to replace [react-native-salute](https://github.com/equinor/react-native-salute)

## Must have

- [ ] Add new notifications
- [ ] Able to dismiss notifications

### Compatibility
- [ ] iOS
- [ ] iPad OS
- [ ] Web

### Notification types
- [ ] Info
- [ ] Warning
- [ ] Error
- [ ] Success

## Wants
- [ ] Able to add multiple notifications

**Comment by tormodAase** [comment]
My suggestion for how to implement this: Create a `Provider`, a custom hook, and a `Screen` component.

- The `Provider` would save the state with `Context`
- The hook would provide the context. Class components will have to fetch the context with [contextType](https://reactjs.org/docs/context.html#classcontexttype)
- The `Screen` component would act as a normal `View`/`SafeAreaView`/`ScrollView` but display notifications on top. Could also display environment banner and service message, but then we would have to make adjustments to the Service Message component.

Apps would implement it like this:

App.tsx
```tsx
const App = () => {
  return <Notifications.Provider>
    ...
    ...
  </Notifications.Provider>
}
```

SomePage.tsx
```tsx
const SomePage = () => {
  const {addNotification} = useNotifications()
  if (somethingWentWrong) {
    addNotification({message: "error message", type: "error"})
  }
  return <Screen safeAreaView>
    // content
  </Screen>
}
```

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue

PS: We have a new package for this: [`@equinor/mad-toast`](https://equinor.github.io/mad/docs/mad-toast/introduction/)!
