### ISSUE TITLE
Polish up the design for existing components

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#128]
A designer should go over the existing components and make sure that the components align with EDS.

TODO: Add screenshots of existing components

**Comment by dbjoEq** [comment]
**Settings screen**


![Image](https://user-images.githubusercontent.com/99209297/214008878-52448ebc-d7fd-4068-8cf1-8220cd8d0256.png)


**Feedback screen**


![Image](https://user-images.githubusercontent.com/99209297/214008959-3364dfce-3e2f-4bb8-bc83-30a55502e292.png)


**Release note screen**


![Image](https://user-images.githubusercontent.com/99209297/214009834-2392ce4e-1584-4189-a19e-e373fe8f89e2.png)


**Onboarding screen**


![Image](https://user-images.githubusercontent.com/99209297/214009272-5b3217df-f9fc-478d-a5df-9d3ae31080e6.png)


**Login screen**


![Image](https://user-images.githubusercontent.com/99209297/214009471-f1876cc0-613e-4a4c-abb6-c1e743d8ba8b.png)


**About screen**


![Image](https://user-images.githubusercontent.com/99209297/214009323-ee776ed5-2667-4395-9479-a325fe43daf9.png)

**Comment by dbjoEq** [comment]
https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?node-id=1%3A2&t=sWUu13JJYa9WhZ7L-1

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
