### ISSUE TITLE
Application Insights count for events is doubled

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#132]
The count for each event in Application Insights is double of what's the reality. For example the count for the event `Authentication AUTOMATIC .` should have been 2 since I only opened the app twice in that timeframe, but the count for that event is 4. The example is from testing with [equinor/mad-project-hearing-test-client](https://github.com/equinor/mad-project-hearing-test-client).
<img width="870" alt="image" src="https://user-images.githubusercontent.com/47424077/216322774-ba76bc99-5c7b-4885-bf90-71e807539496.png">

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
