### ISSUE TITLE
MSAL authentication

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expo-core#15]
Due to issues with Expo Auth, we have to move to MSAL. We will use react-native-msal to replace Expo authsession. For testing the implementation, we will use Expense and pay.

**Comment by tormodAase** [comment]
@ntorsen This is available to test now in Expense and pay test and qa on testflight. 
You should be able to login, and get a list of travel expenses from SAP on the next screen. If you instead get a bunch of weird JSON, that means the authentication did not work properly.

The sign out button is in the settings screen.

Once you've logged in, and close the app, you should automatically log in the next time you open the app (if the accesstoken/refreshtoken is still valid). If you sign out, you have to login manually next time you open the app.

The web version of the authentication also has to be tested, but we haven't deployed the web version of expense and pay yet. Hopefully that will be fixed next week.

Let me know if you have any questions!

**Comment by ntorsen** [comment]
@tormodAase I get a bunch of weird JSON after login and looking at travel expenses for both test and qa.
![image](https://user-images.githubusercontent.com/89014017/156354441-557c75f6-6a04-4c0d-9f6d-da4d030377b9.png)

Also I get text msauth.com.equinor. employee.test://auth (Test) and msauth.com.equinor.employee.qa://auth (Qa) under "Login" button.
