### ISSUE TITLE
ServiceMessage: Banner is pressable but nothing happens

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#165]
When pressing the `ServiceBanner`(the `🔗` and `X` buttons works as intended) when displaying a service message the banner turns dark on press, but this doesn't do anything with the service message. Should it open a modal when the banner is pressed or should it dismiss it, or something else?

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
