### ISSUE TITLE
LoginScreen redesign

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expo-core#22]
Should we use the same design as we have used for apps previously? Is the old design aligned with [EDS](eds.equinor.com)?

**Comment by dbjoEq** [comment]
@tormodAase yes sure! :)

**Comment by SegarJJ** [comment]
for input, the current splash screens I think are done with code, not from a stretched image.  

Another concern I had what about how the app feels when it is launched and we get to the login page.   Today with a few apps we experience something cringeworthy.... what could be done to make this a bit more smooth?   IDK.

https://user-images.githubusercontent.com/23700786/156555417-c976f55c-a1c0-4c56-ab43-b65285d3e337.MP4

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
