### ISSUE TITLE
SettingsScreen redesign

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expo-core#23]

**Comment by dbjoEq** [comment]
This is the targeted design. 

![Skjermbilde 2022–03–16 kl  09 40 23](https://user-images.githubusercontent.com/99209297/158550483-dd2c4d74-5439-4ceb-942a-e4a8d2159398.png)

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
