### ISSUE TITLE
GDEXPO-24 - Update README.md with info on how to use the template

### ISSUE THREAD

**Issue by SegarJJ** [equinor/mad-expo-core#34]
Update README.md with info on how to use the template.

* How to test locally with mad-expo-core (npm run refresh-core)
* How to use app.json
* How to use Colors from mad-expo-core and ProjectColors from template/project
* Which components should be added to template / mad-expo-core
* Commit style (Semantic versioning)
* How to change buttons in SettingsScreen (template/configs/SettingsConfig.tsx)
* How to change questions/values in OnboardingScreen (template/configs/OnboardingConfig.tsx)
* Appreciate contribution and feedback
                    
```

Key: GDEXPO-24




```

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
