### ISSUE TITLE
GDEXPO-21 - Force Settings/Feedback/Onboarding/Login screens to use light mode

### ISSUE THREAD

**Issue by SegarJJ** [equinor/mad-expo-core#37]
Force Settings/Feedback/Onboarding/Login screens to use light mode. This needs to be fixed in "mad-expo-core". Possibly move Themed.tsx from "mad-react-native-expo-template" to "mad-expo-core".
                    
```

Key: GDEXPO-21




```

**Comment by dansvend** [comment]
The theme can be set for React Navigation in each app with the `colorScheme`-prop on the `Navigation`-component in `App.tsx` and should not be hard coded in the screens in `mad-expo-core`. We want React Navigation to control the color scheme to be able to easier implement dark mode in the future.

```JSX
<SafeAreaProvider>
  <Navigation colorScheme="light" />
  <StatusBar style="dark" />
</SafeAreaProvider>
```
