### ISSUE TITLE
Change from custom tabBar to React Navigation tabBar

### ISSUE THREAD

**Issue by SegarJJ** [equinor/mad-expo-core#38]
Change from custom TabBar to React Navigation TabBar.

```JSX
<BottomTab.Navigator
  initialRouteName="Home"
  tabBarOptions={{
    labelStyle: { fontFamily: "Equinor-Medium", fontSize: 12 },
    activeTintColor: Colors.EQUINOR_PRIMARY,
    inactiveTintColor: Colors.GRAY_5,
    style: {
      shadowOpacity: 0.3,
      shadowRadius: 0,
      shadowColor: "black",
      shadowOffset: { height: -0.5, width: 0 },
      backgroundColor: "#fff",
    },
  }}>        
```

**Comment by dansvend** [comment]
This belongs to [mad-react-native-expo-template](https://github.com/equinor/mad-react-native-expo-template) and was implemented in commit [59e2747aa628c98a136d780f927332fd5b376d42](https://github.com/equinor/mad-react-native-expo-template/commit/59e2747aa628c98a136d780f927332fd5b376d42).
