### ISSUE TITLE
ReleaseNotesScreen

### ISSUE THREAD

**Issue by SegarJJ** [equinor/mad-expo-core#46]
Create a `ReleaseNotesScreen`-component. We currently have one in WorkOrders called `FeatureScreen`which can be a starting point for this task. We need to decide on where we should fetch the release notes from.

**Comment by tormodAase** [comment]
I think the best solution here would be standard-version. We would need to create a component in mad expo core for reading changelog from github

**Comment by tormodAase** [comment]
Reading from github might be hard, so another solution might be to read the changelog from the project itself

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
