### ISSUE TITLE
GDEXPO-1 - Create the ExpoRN-template for MAD mobile/web apps

### ISSUE THREAD

**Issue by SegarJJ** [equinor/mad-expo-core#47]
Get to know Expo : 
*[https://docs.expo.io/|https://docs.expo.io/|smart-link]  

Expo Template for apps:

* Add to Github : [https://github.com/equinor/mad-react-native-expo-template|https://github.com/equinor/mad-react-native-expo-template|smart-link]  
* Add Readme details
* etc ?
                    
```

Key: GDEXPO-1

Assignee: Josh Segar


```

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
