### ISSUE TITLE
iOS and Web compatibility

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#51]
Make sure that all components work on both iOS and Web.

### LoginButton.tsx

- [ ] iOS
- [ ] Web

### Button.tsx

- [ ] iOS
- [ ] Web

### Checkbox.tsx

- [ ] iOS
- [ ] Web

### IconButton.tsx

- [ ] iOS
- [ ] Web

### RadioButton.tsx

- [ ] iOS
- [ ] Web

### SimpleInfoItem.tsx

- [ ] iOS
- [ ] Web

### Spinner.tsx

- [ ] iOS
- [ ] Web

### TextLink.tsx

- [ ] iOS
- [ ] Web

### Typography.tsx

- [ ] iOS
- [ ] Web

### Banner.tsx

- [ ] iOS
- [ ] Web

### DetailsTable.tsx

- [ ] iOS
- [ ] Web

### NavigationList.tsx

- [ ] iOS
- [ ] Web

### SettingsButton.tsx

- [ ] iOS
- [ ] Web

### FeedbackScreen.tsx

- [ ] iOS
- [ ] Web

### LoginScreen.tsx

- [ ] iOS
- [ ] Web

### OnboardingScreen.tsx

- [ ] iOS
- [ ] Web

### SettingsScreen.tsx

- [ ] iOS
- [ ] Web

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
