### ISSUE TITLE
AuthContext

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#60]
Create an `AuthContext`-component. The component should wrap the `Navigation`-component in `App.tsx` when used to make sure you have to be authenticated to reach all routes in the app. This is especially important on web since you can easily go directly to any routes by changing the URL without following the navigation flow in the app. The component has already been implemented in [WorkORders](https://github.com/equinor/mad-project-ah-workorders/blob/develop/navigation/AuthContext.tsx) and [Notifications](https://github.com/equinor/mad-project-ah-notification/blob/develop/app/containers/AuthContext.tsx)

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
