### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#65]
Publish this package to either [npmjs.com](https://www.npmjs.com/) or GitHub.

- [ ] Find a good way to handle automatic generation of changelog based on [Conventional Commits]. Since [standard-version](https://github.com/conventional-changelog/standard-version) is deprecated and recommends [release-please](https://github.com/googleapis/release-please) we could use this.

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
