### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-expo-core#68]
Merge colors into one file. Currently we have two locations for colors:

- `src/assets/color/colors.ts`
- `src/stylesheets/colors.ts`

To do:

- [ ] Merge colors from both locations into one file
- [ ] Update imports and usage for components using colors from the file you're deleting after moving colors to the other file

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
