### ISSUE TITLE
Add ReleaseNotes screen

### ISSUE THREAD

**Issue by HaakonSvane** [equinor/mad-expo-core#92]
Add a release notes screen.
The screen should display new release notes that the user has not yet seen and also provide a way to display all release notes for the app.
At the time of writing, the [release notes API](https://mad-api-dev.azurewebsites.net/swagger/index.html?urls.primaryName=V1.1) (dev) expose the following relevant endpoints (**note: v1.1**):

![Screenshot 2022-09-30 at 10 45 21](https://user-images.githubusercontent.com/36899138/193230926-e3e08e4d-5ff2-4710-8893-acdff8db22de.png)

Also, if possible, any possible tie-ins with #91 could be considered

**Comment by PtjeEquinor** [comment]
The release notes screen at startup is now implemented, but not with access from settings and option to display all releasenotes

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
