### ISSUE TITLE
Track userID

### ISSUE THREAD

**Issue by dbjoEq** [equinor/mad-expo-core#94]
There seems to be an issue with the user id being sent to application insights. So we need to have a look into why the id being sent is not consistently the same.

**Comment by mglendrange** [comment]
This is the hashing that is done in Echo:

![image](https://user-images.githubusercontent.com/6025616/194006412-9eb5990a-4937-4655-9d2b-e7425189634c.png)

We implement a unit test in order to see that we get the same result from our hash

**Comment by tormodAase** [comment]
This package is getting phased out, and we do not plan to make any improvements unless they are critical for the remaining apps. Closing this issue
